// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBakn4OiIebHhb39HJF3XBMFyTX9g75CJo',
    appId: '1:672928219309:web:f062e86d6c3da7827b8624',
    messagingSenderId: '672928219309',
    projectId: 'chathive-f6b33',
    authDomain: 'chathive-f6b33.firebaseapp.com',
    storageBucket: 'chathive-f6b33.firebasestorage.app',
    measurementId: 'G-PLSZ4CFMW7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBliSPqmSAiB5hk1H8tMlppLVhDUS7eVGE',
    appId: '1:672928219309:android:9e4a6a90219050807b8624',
    messagingSenderId: '672928219309',
    projectId: 'chathive-f6b33',
    storageBucket: 'chathive-f6b33.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhD1Se1j_O1JbyHQXghmR3b_oGoex_Ngk',
    appId: '1:672928219309:ios:754daf53e2f1c94a7b8624',
    messagingSenderId: '672928219309',
    projectId: 'chathive-f6b33',
    storageBucket: 'chathive-f6b33.firebasestorage.app',
    androidClientId: '672928219309-cfnmnk39du2blee7e8jhdknbfm3c92ar.apps.googleusercontent.com',
    iosClientId: '672928219309-pe2789kkd4b3rv8nmodpko8e72i7p7m8.apps.googleusercontent.com',
    iosBundleId: 'com.example.distributedApplicationHive',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhD1Se1j_O1JbyHQXghmR3b_oGoex_Ngk',
    appId: '1:672928219309:ios:754daf53e2f1c94a7b8624',
    messagingSenderId: '672928219309',
    projectId: 'chathive-f6b33',
    storageBucket: 'chathive-f6b33.firebasestorage.app',
    androidClientId: '672928219309-cfnmnk39du2blee7e8jhdknbfm3c92ar.apps.googleusercontent.com',
    iosClientId: '672928219309-pe2789kkd4b3rv8nmodpko8e72i7p7m8.apps.googleusercontent.com',
    iosBundleId: 'com.example.distributedApplicationHive',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBakn4OiIebHhb39HJF3XBMFyTX9g75CJo',
    appId: '1:672928219309:web:b9388f726a6213a87b8624',
    messagingSenderId: '672928219309',
    projectId: 'chathive-f6b33',
    authDomain: 'chathive-f6b33.firebaseapp.com',
    storageBucket: 'chathive-f6b33.firebasestorage.app',
    measurementId: 'G-0HESZSTSQ0',
  );
}
